# Look for GLEW.
#
#
#
# This script will define the following variables:
#  
#  GLEW_FOUND         - True iff GLEW is found.
#  GLEW_INCLUDE_DIR   - The location of the GLEW headers.
#  GLEW_LIBRARIES     - A list containing the path of the GLEW libraries.

if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    find_library(GLEW_LIBRARIES GLEW glew PATHS ENV LD_LIBRARY_PATH)

    find_path(GLEW_INCLUDE_DIR GL/glew.h PATHS ENV CPLUS_INCLUDE_PATH)
endif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")

if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    find_library(GLEW_LIBRARIES GLEW glew)

    find_path(GLEW_INCLUDE_DIR OpenGL/glew.h)
endif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

if(${GLEW_LIBRARIES} MATCHES "GLEW_LIBRARIES-NOTFOUND" OR ${GLEW_INCLUDE_DIR} MATCHES "GLEW_INCLUDE_DIR-NOTFOUND")
     set(GLEW_FOUND "No")
else(${GLEW_LIBRARIES} MATCHES "GLEW_LIBRARIES-NOTFOUND" OR ${GLEW_INCLUDE_DIR} MATCHES "GLEW_INCLUDE_DIR-NOTFOUND")
     set(GLEW_FOUND "Yes")
endif(${GLEW_LIBRARIES} MATCHES "GLEW_LIBRARIES-NOTFOUND" OR ${GLEW_INCLUDE_DIR} MATCHES "GLEW_INCLUDE_DIR-NOTFOUND")

if(${DEBUG_FINDOPENCL} MATCHES "Yes")

     message("GLEW_LIBRARIES " ${GLEW_LIBRARIES})

     message("GLEW_INCLUDE_DIR " ${GLEW_INCLUDE_DIR})

endif(${DEBUG_FINDOPENCL} MATCHES "Yes")
